context:
  version: "0.8.13"

package:
  name: jacoco
  version: ${{ version }}

source:
  url: https://github.com/jacoco/jacoco/archive/v${{ version }}.tar.gz
  sha256: d9e832851bb61a604af938350762341905dc909ddbd2062516862633ffa62603

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - maven
    - openjdk =17
    - unzip
  run:
    - openjdk

tests:
  - script:
      - jacoco --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE.md
    - target/generated-resources/licenses/
  summary: Java Code Coverage Library
  homepage: https://github.com/jacoco/jacoco
  repository: https://github.com/jacoco/jacoco

extra:
  recipe-maintainers:
    - danielnachun
