context:
  version: 0.8.12

package:
  name: jacoco
  version: ${{ version }}

source:
  url: https://github.com/jacoco/jacoco/archive/v${{ version }}.tar.gz
  sha256: 34cba4b114df609607c282eda7d6d2365968576920796941bacdab9c9e441d74

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - maven
    - openjdk =17
    - unzip
  run:
    - openjdk

tests:
  - script:
      - jacoco --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE.md
    - target/generated-resources/licenses/
  summary: Java Code Coverage Library
  homepage: https://github.com/jacoco/jacoco
  repository: https://github.com/jacoco/jacoco

extra:
  recipe-maintainers:
    - danielnachun
